name: 'Base'
description: 'Base for runners'

on:
  push:
    branches:
      - main
      - release/*
  pull_request:
    branches:
      - main
      - release/*

runs:
  using: composite

  steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        persist-credentials: false

    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: yarn

    - name: Read pkg.json
      uses: actions/github-script@v6
      id: package
      with:
        script: |
          try {
            const fs = require('fs')
            const jsonString = fs.readFileSync('./package.json')
            const pkg = JSON.parse(jsonString)
            return Object.keys(pkg.scripts)
          } catch(err) {
            core.error("Error while reading or parsing the JSON")
            core.setFailed(err)
          }
